export const approvalPage = `<!doctype html>
<html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Mini ERP Approval Console</title>
<style>
:root{color-scheme:dark;font-family:Inter,ui-sans-serif,system-ui,sans-serif;background:#0f172a;color:#e2e8f0}body{margin:0;background:radial-gradient(circle at top right,#1e3a5f,#0f172a 55%);min-height:100vh}.shell{max-width:1050px;margin:0 auto;padding:36px 22px}.eyebrow{color:#67e8f9;font-size:12px;letter-spacing:.16em;text-transform:uppercase;font-weight:700}.hero{display:flex;justify-content:space-between;gap:24px;align-items:end;margin-bottom:24px}.hero h1{font-size:34px;margin:8px 0}.hero p{color:#94a3b8;margin:0;max-width:640px}.badge{border:1px solid #334155;border-radius:999px;padding:8px 12px;color:#a5f3fc;background:#0f2534;white-space:nowrap}.grid{display:grid;grid-template-columns:1.1fr .9fr;gap:18px}.card{background:rgba(15,23,42,.78);border:1px solid #334155;border-radius:16px;padding:20px;box-shadow:0 16px 40px #02061755}.card h2{font-size:15px;margin:0 0 14px;color:#f8fafc}.request{font-size:18px;line-height:1.5;color:#f8fafc}.muted{color:#94a3b8}.metric{display:flex;justify-content:space-between;border-top:1px solid #263449;padding:11px 0}.metric:first-of-type{border-top:0}.metric strong{color:#67e8f9}.status{display:inline-block;border-radius:999px;padding:5px 9px;font-size:12px;font-weight:700;background:#334155;color:#cbd5e1}.status.pending{background:#713f12;color:#fde68a}.status.approved{background:#164e63;color:#a5f3fc}.status.completed{background:#14532d;color:#bbf7d0}.actions{display:flex;gap:10px;flex-wrap:wrap;margin-top:18px}button{border:0;border-radius:10px;padding:11px 15px;background:#22d3ee;color:#082f49;font-weight:800;cursor:pointer}button.secondary{background:#334155;color:#e2e8f0}button:disabled{opacity:.4;cursor:not-allowed}.trace{font-family:ui-monospace,SFMono-Regular,Consolas,monospace;font-size:12px;line-height:1.65;max-height:330px;overflow:auto;color:#cbd5e1}.trace span{color:#67e8f9}.error{margin-top:14px;padding:12px;border-radius:10px;background:#450a0a;color:#fecaca}.wide{grid-column:1/-1}.hidden{display:none}@media(max-width:760px){.hero{display:block}.badge{display:inline-block;margin-top:16px}.grid{grid-template-columns:1fr}}
</style></head><body><main class="shell"><div class="hero"><div><div class="eyebrow">AI-FIRST MINI ERP</div><h1>Approval Console</h1><p>Watch a bounded agent flow from inventory analysis to an approved, idempotent ERP-style mutation.</p></div><div id="provider" class="badge">DETERMINISTIC AGENT</div></div>
<div class="grid"><section class="card"><h2>1. User request</h2><div class="request">Which open orders are at risk because of inventory shortages?</div><div class="actions"><button id="analyze">Run agent analysis</button></div><div id="progress" class="muted" aria-live="polite"></div><div id="analysis" class="hidden"></div></section>
<section class="card"><h2>2. Action state</h2><div id="actionState" class="muted">No action proposed yet.</div><div class="actions"><button id="approve" disabled>Approve as Operations Manager</button><button id="execute" class="secondary" disabled>Execute approved action</button></div><div id="error"></div></section>
<section class="card"><h2>3. Recommendation</h2><div id="recommendation" class="muted">Run the agent to generate a grounded recommendation.</div></section>
<section class="card"><h2>4. Result</h2><div id="result" class="muted">No ERP-style mutation has been executed.</div></section>
<section class="card wide"><h2>5. Trace summary</h2><div id="trace" class="trace muted">Lifecycle events will appear here.</div></section></div></main>
<script>
const $=id=>document.getElementById(id);let state;
async function call(path){const controller=new AbortController();const timeout=setTimeout(()=>controller.abort(),90000);try{const response=await fetch(path,{method:'POST',signal:controller.signal});const data=await response.json();if(!response.ok)throw new Error(data.error||'Request failed');return data}catch(error){if(error.name==='AbortError')throw new Error('The agent request timed out after 90 seconds. Check the server terminal and try again.');throw error}finally{clearTimeout(timeout)}}
function status(s){return '<span class="status '+s.toLowerCase()+'">'+s+'</span>'}
function render(){if(!state)return;$('provider').textContent=state.provider+' AGENT';if(state.analysis){$('analysis').className='';$('analysis').innerHTML='<p class="muted">'+state.analysis.response+'</p><div class="metric"><span>Read tools</span><strong>'+state.analysis.toolCalls.length+'</strong></div><div class="metric"><span>Finding</span><strong>SO-1001 / P-001</strong></div>'}$('recommendation').innerHTML=state.recommendation?'<div class="metric"><span>Product</span><strong>'+state.recommendation.productId+'</strong></div><div class="metric"><span>Quantity</span><strong>'+state.recommendation.quantity+'</strong></div><div class="metric"><span>Linked order</span><strong>'+state.recommendation.linkedOrderId+'</strong></div><p class="muted">'+state.recommendation.reason+'</p>':'Run the agent to generate a grounded recommendation.';$('actionState').innerHTML=state.action?'<div class="metric"><span>Action ID</span><strong>'+state.action.actionId+'</strong></div><div class="metric"><span>Status</span>'+status(state.phase==='PENDING_APPROVAL'?'PENDING':state.phase)+'</div>':'No action proposed yet.';$('approve').disabled=state.phase!=='PENDING_APPROVAL';$('execute').disabled=state.phase!=='APPROVED';$('result').innerHTML=state.replenishmentRequest?'<div class="metric"><span>Request ID</span><strong>'+state.replenishmentRequest.requestId+'</strong></div><div class="metric"><span>Status</span>'+status(state.replenishmentRequest.status)+'</div><div class="metric"><span>Duplicate execution</span><strong>'+state.duplicateExecutionRequestId+'</strong></div>':'No ERP-style mutation has been executed.';$('trace').innerHTML=state.traceEvents.length?state.traceEvents.map(e=>'<div><span>'+e.type+'</span> — '+e.summary+'</div>').join(''):'Lifecycle events will appear here.'}
async function run(action){$('error').innerHTML='';$('progress').textContent=action==='/api/analyze'?'Agent is analyzing orders and inventory…':'Applying the approved workflow…';$('analyze').disabled=true;$('approve').disabled=true;$('execute').disabled=true;try{state=await call(action);render()}catch(error){$('error').innerHTML='<div class="error">'+error.message+'</div>'}finally{$('progress').textContent='';render()}}
$('analyze').onclick=()=>run('/api/analyze');$('approve').onclick=()=>run('/api/approve');$('execute').onclick=()=>run('/api/execute');fetch('/api/state').then(r=>r.json()).then(s=>{state=s;render()});
</script></body></html>`;
